### ISSUE TITLE
google-protobuf depended by onnx is v2.6.1，but it conflicts with python3，maybe only python2 works well!

### ISSUE THREAD

**Issue by gaoxueyi0532** [tianyic/only_train_once#22]
When i use oTo code to train my model，an error ecounterd，error details:
================================================
Traceback (most recent call last):
  File "oto_train.py", line 216, in <module>
    main(args.cfg)
  File "oto_train.py", line 181, in main
    oto.compress()
  File "/mnt/home/oToV2/only_train_once/__init__.py", line 67, in compress
    dynamic_axes=dynamic_axes)
  File "/mnt/home/oToV2/only_train_once/compression/compression.py", line 27, in automated_compression
    import onnx
  File "/opt/conda/lib/python3.7/site-packages/onnx/__init__.py", line 9, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors
  File "/opt/conda/lib/python3.7/site-packages/onnx/external_data_helper.py", line 10, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/opt/conda/lib/python3.7/site-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ONNX_REL_1_7_ml_pb2 import *  # noqa
  File "/opt/conda/lib/python3.7/site-packages/onnx/onnx_ONNX_REL_1_7_ml_pb2.py", line 9, in <module>
    from google.protobuf import reflection as _reflection
  File "/opt/conda/lib/python3.7/site-packages/google/protobuf/reflection.py", line 68, in <module>
    from google.protobuf.internal import python_message
  File "/opt/conda/lib/python3.7/site-packages/google/protobuf/internal/python_message.py", line 72, in <module>
    from google.protobuf.internal import decoder
  File "/opt/conda/lib/python3.7/site-packages/google/protobuf/internal/decoder.py", line 167, in <module>
    _DecodeVarint = _VarintDecoder((1 << 64) - 1, long)
NameError: name 'long' is not defined
==================================================

Maybe python2 works well with the google-protobuf v2.6.1 according to the error because long type is allowd in python2，but python2 is outdated as you know, how to solve the problem？

**Comment by tianyic** [comment]
@gaoxueyi0532 Thanks for reaching out. OTO is only tested on Python3 but not python2. 

The error looks like the conflict between `onnx`[https://onnx.ai/onnx/intro/python.html] and `google-protobuf`. There is not that much things can be done on OTO side. Please check the onnx version.
