### ISSUE TITLE
pruning transformer-based model

### ISSUE THREAD

**Issue by huanghmingyue** [tianyic/only_train_once#54]
Hi. Thank you for your contribution. 
Can OTO be used for pruning Transformers? I want to apply it to a DETR-like object detection model(DINO:https://github.com/IDEA-Research/DINO). Is this feasible?
I tried and got this error:
---------------------------------------------------------------------------------------------------------------------------------------
OTO graph constructor
graph build
/home/chendu/huangmingyue/DINO/util/misc.py:406: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  max_size_i = torch.max(torch.stack([img.shape[i] for img in tensor_list]).to(torch.float32)).to(torch.int64)
/home/chendu/huangmingyue/DINO/util/misc.py:416: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for img in tensor_list:
/home/chendu/huangmingyue/DINO/models/dino/position_encoding.py:95: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_tx = self.temperatureW ** (2 * (dim_tx // 2) / self.num_pos_feats)
/home/chendu/huangmingyue/DINO/models/dino/position_encoding.py:99: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_ty = self.temperatureH ** (2 * (dim_ty // 2) / self.num_pos_feats)
/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/nn/functional.py:2359: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  _verify_batch_size([input.size(0) * input.size(1) // num_groups, num_groups] + list(input.size()[2:]))
/home/chendu/huangmingyue/DINO/models/dino/deformable_transformer.py:289: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  spatial_shapes = torch.as_tensor(spatial_shapes, dtype=torch.long, device=src_flatten.device)
/home/chendu/huangmingyue/DINO/models/dino/deformable_transformer.py:289: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  spatial_shapes = torch.as_tensor(spatial_shapes, dtype=torch.long, device=src_flatten.device)
/home/chendu/huangmingyue/DINO/models/dino/deformable_transformer.py:479: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for lvl, (H_, W_) in enumerate(spatial_shapes):
/home/chendu/huangmingyue/DINO/models/dino/deformable_transformer.py:481: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ref_y, ref_x = torch.meshgrid(torch.linspace(0.5, H_ - 0.5, H_, dtype=torch.float32, device=device),
/home/chendu/huangmingyue/DINO/models/dino/deformable_transformer.py:482: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  torch.linspace(0.5, W_ - 0.5, W_, dtype=torch.float32, device=device))
/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/chendu/huangmingyue/DINO/models/dino/ops/modules/ms_deform_attn.py:92: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (input_spatial_shapes[:, 0] * input_spatial_shapes[:, 1]).sum() == Len_in
/home/chendu/huangmingyue/DINO/models/dino/ops/modules/ms_deform_attn.py:102: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 2:
/home/chendu/huangmingyue/DINO/models/dino/utils.py:30: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for lvl, (H_, W_) in enumerate(spatial_shapes):
/home/chendu/huangmingyue/DINO/models/dino/utils.py:35: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  grid_y, grid_x = torch.meshgrid(torch.linspace(0, H_ - 1, H_, dtype=torch.float32, device=memory.device),
/home/chendu/huangmingyue/DINO/models/dino/utils.py:36: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  torch.linspace(0, W_ - 1, W_, dtype=torch.float32, device=memory.device))
/home/chendu/huangmingyue/DINO/models/dino/deformable_transformer.py:682: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if reference_points.shape[-1] == 4:
/home/chendu/huangmingyue/DINO/models/dino/utils.py:143: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = 10000 ** (2 * (dim_t // 2) / 128)
/home/chendu/huangmingyue/DINO/models/dino/utils.py:150: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pos_tensor.size(-1) == 2:
/home/chendu/huangmingyue/DINO/models/dino/utils.py:152: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif pos_tensor.size(-1) == 4:
/home/chendu/huangmingyue/DINO/models/dino/ops/modules/ms_deform_attn.py:106: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif reference_points.shape[-1] == 4:
/home/chendu/huangmingyue/DINO/models/dino/dino.py:330: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for a, b in zip(outputs_class[:-1], outputs_coord[:-1])]
/home/chendu/huangmingyue/DINO/models/dino/dino.py:304: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if hs_enc.shape[0] > 1:
Traceback (most recent call last):
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 1032, in _convert_padding_node
    padding = [sym_help._get_const(v, "i", "padding") for v in input_list]
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 1032, in <listcomp>
    padding = [sym_help._get_const(v, "i", "padding") for v in input_list]
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 112, in _get_const
    raise RuntimeError("ONNX symbolic expected a constant value of the {} argument, got `{}`".format(arg_name, value))
RuntimeError: ONNX symbolic expected a constant value of the padding argument, got `657 defined in (%657 : Long(requires_grad=0, device=cpu) = onnx::Sub(%631, %651) # /home/chendu/huangmingyue/DINO/util/misc.py:417:0
)`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OTO.py", line 32, in <module>
    oto = OTO(model, example_inputs)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/only_train_once/__init__.py", line 16, in __init__
    self.initialize(model=self._model, dummy_input=self._dummy_input, skip_patterns=self._skip_patterns, strict_out_nodes=self._strict_out_nodes)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/only_train_once/__init__.py", line 35, in initialize
    self._graph = Graph(model, dummy_input, skip_patterns=skip_patterns, strict_out_nodes=strict_out_nodes)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/only_train_once/graph/graph.py", line 68, in __init__
    self.build(model, dummy_input)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/only_train_once/graph/graph.py", line 77, in build
    trace_graph = self._get_trace_graph(model, dummy_input, optimized_onnx=self.trace_onnx)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/only_train_once/graph/graph.py", line 426, in _get_trace_graph
    trace_graph = torch.onnx._optimize_trace(trace_graph, torch.onnx.OperatorExportTypes.ONNX)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/__init__.py", line 353, in _optimize_trace
    return utils._optimize_graph(graph, operator_export_type)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 1044, in constant_pad_nd
    padding = _convert_padding_node(padding)
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 1034, in _convert_padding_node
    return sym_help._onnx_opset_unsupported_detailed("Pad", 9, 11, "The sizes of the padding must be constant")
  File "/home/chendu/anaconda3/envs/hmy/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 272, in _onnx_opset_unsupported_detailed
    "opset {}. {}. Please try opset version {}.".format(op_name, current_opset, reason, supported_opset))
RuntimeError: Unsupported: ONNX export of Pad in opset 9. The sizes of the padding must be constant. Please try opset version 11.

**Comment by iamanigeeit** [comment]
@huanghmingyue I think you are using a very old version of pytorch. Try upgrading python and pytorch.

**Comment by tianyic** [comment]
@huanghmingyue I agreed with @iamanigeeit that you need to consider use a newer pytorch for getting tracing graph. Transformer is supported such as [bert](https://github.com/tianyic/only_train_once/blob/main/sanity_check/test_bert.py) and [LLM](https://github.com/tianyic/only_train_once/blob/main/sanity_check/test_llamav1.py). But some new transformers may require implement some unseen operators.
